[[commands]]
name = "cmd"
command = "cmd.exe"

[[commands]]
name = "lua"
command = "lua"

[[commands]]
name = "powershell"
command = "powershell.exe"

[project]
name = "azerothcore-wotlk"
description = "AzerothCore WotLK with pfQuest extractor"
