pfDB["items"]["enUS"] = {
  [17] = "Martin Fury",
  [25] = "Worn Shortsword",
  [35] = "Bent Staff",
  [36] = "Worn Mace",
  [37] = "Worn Axe",
  [38] = "Recruit's Shirt",
  [39] = "Recruit's Pants",
  [40] = "Recruit's Boots",
  [41] = "OLDRecruit's Belt",
  [42] = "OLDSquire's Belt",
  [43] = "Squire's Boots",
  [44] = "Squire's Pants",
  [45] = "Squire's Shirt",
  [46] = "OLDFootpad's Belt",
  [47] = "Footpad's Shoes",
}
