pfDB["objects"]["enUS"] = {
  [30] = "Dalaran Forge Spell Focus",
  [31] = "Old Lion Statue",
  [32] = "Sunken Chest",
  [33] = "Locked Chest",
  [34] = "Old Jug",
  [35] = "Captain's Footlocker",
  [36] = "Broken Barrel",
  [37] = "Eliza's Tombstone",
  [38] = "Captain Sanders Chest",
  [4] = "Bonfire Damage",
  [41] = "Ambassador's Locker",
  [47] = "Wanted: Lieutenant Fangore",
  [52] = "Fall of Gurubashi",
  [54] = "The Emperor's Tomb",
  [55] = "A half-eaten body",
}
